export default {
    name:'skills',
    title:'Skills',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string',
        },
        {
            name:'img',
            title:'Image',
            type:'image',
            options:{
                hotspot:true
            }
        }
    ]
}